-d C:\Users\xiang\Downloads\BU\RASTIC\WebBlink\FPGA\led_blinker\impl\gwsynthesis\led_trigger.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst C:\Users\xiang\Downloads\BU\RASTIC\WebBlink\FPGA\led_blinker\src\led_trigger.cst
-cfg C:\Users\xiang\Downloads\BU\RASTIC\WebBlink\FPGA\led_blinker\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
